apiVersion: v1
kind: Service
metadata:
  name: controlapp
  namespace: controlapp
  labels:
    run: controlapp
spec:
  type: NodePort
  ports:
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: flask-port
  selector:
    run: controlapp
  externalIPs: ["10.1.2.152"]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlapp
  namespace: controlapp
spec:
  selector:
    matchLabels:
      run: controlapp
  replicas: 2
  template:
    metadata:
      labels:
        run: controlapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values: ["raspi3-110"]
      containers:
        - name: controlapp
          image: sanabriarusso/controlapp:jessie
          imagePullPolicy: Always
          securityContext:
            privileged: False
          ports:
            - containerPort: 8848
              name: flask-port
          resources:
            limits:
              memory: "500Mi"
              cpu: "2"
            requests:
              memory: "50Mi"
              cpu: "1"
